trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BUILD
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(CustomVariable)
  - job: SecondJob
    steps:
    - bash: echo BUILD SecondJob

- stage: DEV
  dependsOn: BUILD
  variables:
    environment:
      Dev
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo $(environment)DeployJob

- stage: QA
  dependsOn: BUILD
  variables:
    environment:
      Dev
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo $(environment)DeployJob

- stage: PROD
  dependsOn: 
  - DEV
  - QA
  variables:
    environment:
      Dev
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo $(environment)DeployJob

