trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BUILD
  jobs:
  - job: FirstJob
    steps:
    - bash: echo BUILD FirstJob
  - job: SecondJob
    steps:
    - bash: echo BUILD SecondJob

- stage: DEV
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeployJob

- stage: QA
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob

- stage: PROD
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob

